apiVersion: v1
kind: Pod
metadata:
  name: cgt
  labels:
    app: cgt
    tier: backend

spec:
  containers:
    - image: mpiorun/capital:latest
      name: cgt
      ports:
        - containerPort: 8080
          name: http

      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5

  terminationGracePeriodSeconds: 5

